---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/transactions":
    get:
      summary: list transactions
      parameters:
      - name: query
        in: query
        description: Optional id to search transaction
        required: false
      responses:
        '200':
          description: successful
    post:
      summary: create transaction
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                input_amount:
                  type: number
                input_currency:
                  type: string
                output_amount:
                  type: number
                output_currency:
                  type: string
              required:
              - customer_id
              - input_amount
              - input_currency
              - output_amount
              - output_currency
  "/api/v1/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      responses:
        '200':
          description: successful
    patch:
      summary: update transaction
      responses:
        '200':
          description: successful
    put:
      summary: update transaction
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                input_amount:
                  type: number
                input_currency:
                  type: string
                output_amount:
                  type: number
                output_currency:
                  type: string
              required:
              - customer_id
              - input_amount
              - input_currency
              - output_amount
              - output_currency
servers:
- url: http://127.0.0.1:3000
  description: Development environment
- url: https://azatest.onrender.com
  description: Production environment
