---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/transactions":
    get:
      summary: list transactions
      responses:
        '200':
          description: successful
    post:
      summary: create transaction
      responses:
        '200':
          description: successful
  "/api/v1/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      responses:
        '200':
          description: successful
    patch:
      summary: update transaction
      responses:
        '200':
          description: successful
    put:
      summary: update transaction
      responses:
        '200':
          description: successful
    delete:
      summary: delete transaction
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
